#define _CRT_SECURE_NO_WARNINGS

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>



#include "lfc_unicode.h"
#include "lfc_utils.h"
#include "lfc_font.h"


/**
 * @brief Write font metadata header to an output C header file
 *
 * This function generates a formatted comment block containing font information
 * at the beginning of the output C header file. The header includes essential
 * metadata about the font for documentation and debugging purposes.
 *
 * @param export_file Pointer to the output FILE stream where the font header
 *                    will be written. Must be opened in write mode.
 * @param font_profile Pointer to the FONT_PROFILE structure containing font
 *                     metadata and character data.
 * @param total_bytes Total number of bytes occupied by the font bitmap data
 *                    in the output array. Used to calculate memory footprint.
 * @param write_char_codes Boolean flag indicating whether to include the list
 *                         of character code points in the header.
 *                         - 0: Do not write character codes
 *                         - 1: Write hexadecimal character codes
 *
 * @return int Returns 0 on success, 1 if invalid parameters are provided
 *
 */

int Lfc_Write_Font_Info(FILE* export_file, FONT_PROFILE* font_profile, unsigned int total_bytes, int write_char_codes) {

    //For time stamp
    time_t c_time;
    time(&c_time);

    if (export_file == NULL || font_profile == NULL) {
        return 1;
    }

    fprintf(export_file, "/***************************************************************************************************\n");
    fprintf(export_file, "** Source Font      : %s \n", font_profile->font_name);
    fprintf(export_file, "** Font Size        : %d \n", font_profile->font_size);
    fprintf(export_file, "** Total Bytes      : %-6d \n", total_bytes);
    fprintf(export_file, "** Character Count  : %d \n", font_profile->char_data_len);
    fprintf(export_file, "** Font Format Type : C8 ");

    if (write_char_codes && font_profile->char_data) {
        fprintf(export_file, "\n** Char List          :");
        for (int i = 0; i < font_profile->char_data_len; i++) {
            fprintf(export_file, " 0x%X", (unsigned int)font_profile->char_data[i].char_code);
        }
    }

    fprintf(export_file, "\n** Create Time      : %s", ctime(&c_time));
    fprintf(export_file,   "** Note             : This file is generated by the LFC font converter.");
    fprintf(export_file, "\n****************************************************************************************************/\n");

    return 0;
}